package com.eduramza.mybraziliexapp.extensions

enum class Cryptos( val coin: String){
    BTC("Bitcoin"),
    BCH("Bitcoin-Cash"),
    LTC("Litecoin"),
    ETH("Ethereum"),
    DASH("Dash"),
    ZEC("ZCash"),
    DCR("Decred"),
    XRP("Ripple"),
    USDT("USD Tether"),
    TUSD("True USD"),
    ZRX("Ox"),
    DAI("Colateral DAI Token"),
    PAXG("Paxos Gold"),
    SNGLS("SingularDTV"),
    BRZX("Braziliex Token"),
    GMR("Gimmer"),
    OMG("OmiseGo"),
    GNT("Golem"),
    EPC("Epacoin Token"),
    ABC("Anti Bureaucracy Coin"),
    XMR("Monero"),
    MXT("MartexCoin"),
    SMART("SmartCash"),
    NBR("Nióbio Cash"),
    BSV("Bitcoin SV"),
    CRW("Crown"),
    LCC("Litecoin-Cash"),
    ONIX("Onix"),
    ETC("Ethereum-Classic"),
    IOP("Internet Of People"),
    BTG("Bitcoin-Gold"),
    BNB("Binance Coin"),
    EOS("EOS"),
    PRSP("Prosper"),
    CFTY("Crafty Token"),
    TRX("Tron")
}